version: '3.3'
services:
  pg:
    image: "postgres:latest"
    container_name: "adonis-start.pg"
    volumes:
      - ./data/postgres/db:/data/db
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}

